//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 11:58:10 AM EDT 
//


package mil.navy.safecen.solr.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mil.navy.safecen.solr.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Created_QNAME = new QName("http://mil.navy.safecen/solr", "created");
    private final static QName _Status_QNAME = new QName("http://mil.navy.safecen/solr", "status");
    private final static QName _SummaryId_QNAME = new QName("http://mil.navy.safecen/solr", "summary_id");
    private final static QName _Action_QNAME = new QName("http://mil.navy.safecen/solr", "action");
    private final static QName _ReportType_QNAME = new QName("http://mil.navy.safecen/solr", "report_type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mil.navy.safecen.solr.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MonitorRecord }
     * 
     */
    public MonitorRecord createMonitorRecord() {
        return new MonitorRecord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mil.navy.safecen/solr", name = "created")
    public JAXBElement<XMLGregorianCalendar> createCreated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Created_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mil.navy.safecen/solr", name = "status")
    public JAXBElement<StatusType> createStatus(StatusType value) {
        return new JAXBElement<StatusType>(_Status_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mil.navy.safecen/solr", name = "summary_id")
    public JAXBElement<String> createSummaryId(String value) {
        return new JAXBElement<String>(_SummaryId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mil.navy.safecen/solr", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mil.navy.safecen/solr", name = "report_type")
    public JAXBElement<ReportTypeType> createReportType(ReportTypeType value) {
        return new JAXBElement<ReportTypeType>(_ReportType_QNAME, ReportTypeType.class, null, value);
    }

}
