//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 11:58:10 AM EDT 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://mil.navy.safecen/solr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://mil.navy.safecen/solr",
		xmlns = {@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://mil.navy.safecen/solr", prefix = "nsc") },
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mil.navy.safecen.solr.jaxb;

