//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.27 at 11:58:10 AM EDT 
//


package mil.navy.safecen.solr.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReportTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AVIATION_MISHAP"/>
 *     &lt;enumeration value="AVIATION_HAZARD"/>
 *     &lt;enumeration value="AV_INITIAL_NOTIFICATION"/>
 *     &lt;enumeration value="CN_INITIAL_NOTIFICATION"/>
 *     &lt;enumeration value="CN_HAZARD"/>
 *     &lt;enumeration value="MV_MISHAP"/>
 *     &lt;enumeration value="AFLOAT_MISHAP"/>
 *     &lt;enumeration value="AFLOAT_HAZARD"/>
 *     &lt;enumeration value="ROD_MISHAP"/>
 *     &lt;enumeration value="ROD_HAZARD"/>
 *     &lt;enumeration value="SHORE_MISHAP"/>
 *     &lt;enumeration value="SHORE_HAZARD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReportTypeType")
@XmlEnum
public enum ReportTypeType {

    AVIATION_MISHAP,
    AVIATION_HAZARD,
    AV_INITIAL_NOTIFICATION,
    CN_INITIAL_NOTIFICATION,
    CN_HAZARD,
    MV_MISHAP,
    AFLOAT_MISHAP,
    AFLOAT_HAZARD,
    ROD_MISHAP,
    ROD_HAZARD,
    SHORE_MISHAP,
    SHORE_HAZARD;

    public String value() {
        return name();
    }

    public static ReportTypeType fromValue(String v) {
        return valueOf(v);
    }

}
